trigger:
  branches:
    include:
      - staging
      - master

jobs:

- job: PublishCommonDataStoreLibrary
  displayName: 'Publish common data store library'
  variables:
    majorProductVersion: 1
    minorProductVersion: 0
    masterMajorMinor: $(majorProductVersion).$(minorProductVersion)
    masterPatchCount: $[counter(variables['masterMajorMinor'], 0)]
    stagingMajorMinor: $(majorProductVersion).$(minorProductVersion)-beta
    stagingPatchCount: $[counter(variables['stagingMajorMinor'], 0)]
    pullRequestMajorMinor: $(majorProductVersion).$(minorProductVersion)-alpha$(variables['system.pullrequest.pullrequestid'])
    pullRequestPatchCount: $[counter(variables['pullRequestMajorMinor'], 0)]
    branchMajorMinor: $(majorProductVersion).$(minorProductVersion)-br$(variables['build.sourcebranch'])
    branchPatchCount: $[counter(variables['branchMajorMinor'], 0)]
  pool:
    vmImage: 'windows-2019'
    displayName: 'Run Test Pipeline and publish package'

  steps:

  # Run npm install
  - task: Npm@1
    displayName: 'Run npm install'
    inputs:
      command: 'install'

  # Run Unit Tests
  - task: Npm@1
    displayName: 'Run Unit Tests'
    inputs:
      command: 'custom'
      customCommand: 'run test'

  # Publish Test Results
  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'junit.xml'
      failTaskOnFailedTests: true

  # Versioning
  # master branch versioning
  - task: Npm@1
    displayName: 'Bump package version - master branch'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    inputs:
      command: 'custom'
      workingDir: $(Build.SourcesDirectory)
      verbose: false
      customCommand: 'version $(majorProductVersion).$(minorProductVersion).$(masterPatchCount) --no-git-tag-version --allow-same-version'
      customRegistry: 'useFeed'
      customFeed: '08d378fd-be72-4c80-9ce4-1a7c754efb98/0cfdd55f-d4ae-47d8-992c-993a5df083d6'

  # staging branch versioning
  - task: Npm@1
    displayName: 'Bump package version - staging branch'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/staging')
    inputs:
      command: 'custom'
      workingDir: $(Build.SourcesDirectory)
      verbose: false
      customCommand: 'version $(majorProductVersion).$(minorProductVersion).$(stagingPatchCount)-beta --no-git-tag-version --allow-same-version'
      customRegistry: 'useFeed'
      customFeed: '08d378fd-be72-4c80-9ce4-1a7c754efb98/0cfdd55f-d4ae-47d8-992c-993a5df083d6'

  # PR versioning for master branch & staging branch
  - task: Npm@1
    displayName: 'Bump package version - PR for master & staging branch'
    condition: and(ne(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.SourceBranch'], 'refs/heads/staging'), eq(variables['Build.Reason'], 'PullRequest'))
    inputs:
      command: 'custom'
      workingDir: $(Build.SourcesDirectory)
      verbose: false
      customCommand: 'version $(majorProductVersion).$(minorProductVersion).0-alpha$(system.pullrequest.pullrequestid)-$(pullRequestPatchCount) --no-git-tag-version --allow-same-version'
      customRegistry: 'useFeed'
      customFeed: '08d378fd-be72-4c80-9ce4-1a7c754efb98/0cfdd55f-d4ae-47d8-992c-993a5df083d6'

  # Name branch prefix to build version (master branch & staging branch)
  - task: Npm@1
    displayName: 'Bump package version - other branch'
    condition: and(ne(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.SourceBranch'], 'refs/heads/staging'), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      command: 'custom'
      workingDir: $(Build.SourcesDirectory)
      verbose: false
      customCommand: 'version $(majorProductVersion).$(minorProductVersion).0-$(Build.BuildId)-$(branchPatchCount) --no-git-tag-version --allow-same-version'
      customRegistry: 'useFeed'
      customFeed: '08d378fd-be72-4c80-9ce4-1a7c754efb98/0cfdd55f-d4ae-47d8-992c-993a5df083d6'

  # Compile
  - task: Npm@1
    displayName: 'Compile ts library'
    inputs:
      command: 'custom'
      customCommand: 'run tsc'

  # Publishes npm package
  - task: Npm@1
    displayName: 'Publish Artifact'
    inputs:
      command: 'publish'
      publishRegistry: 'useFeed'
      publishFeed: '08d378fd-be72-4c80-9ce4-1a7c754efb98/0cfdd55f-d4ae-47d8-992c-993a5df083d6'
