const FixesActionTypesModel = {
  SET_NEW_FIXES: 'fixes/SET_NEW_FIXES',
  SET_PENDING_FIXES: 'fixes/SET_PENDING_FIXES',
  SET_IN_PROGRESS_FIXES: 'fixes/SET_IN_PROGRESS_FIXES',
  SET_IN_REVIEW_FIXES: 'fixes/SET_IN_REVIEW_FIXES',
  SET_COMPLETED_FIXES: 'fixes/SET_COMPLETED_FIXES',
  SET_TERMINATED_FIXES: 'fixes/SET_TERMINATED_FIXES',
};

export default FixesActionTypesModel;
