const FixRequestActionTypesModel = {
  SET_NUMBER_OF_STEPS: 'fixRequest/SET_NUMBER_OF_STEPS',
  ADD_FIX_STEPS_DYNAMIC_ROUTE: 'fixRequest/ADD_FIX_STEPS_DYNAMIC_ROUTE',
  SET_CURRENT_FIX_STEPS_ROUTE_INDEX: 'fixRequest/SET_CURRENT_FIX_STEPS_ROUTE_INDEX',
  ADD_FIX_REQUEST_TAG: 'fixRequest/ADD_FIX_REQUEST_TAG',
  SET_FIX_REQUEST_TAGS: 'fixRequest/SET_FIX_REQUEST_TAGS',
  SET_FIX_TEMPLATE_NAME: 'fixRequest/SET_FIX_TEMPLATE_NAME',
  SET_FIX_TEMPLATE_CATEGORY: 'fixRequest/SET_FIX_TEMPLATE_CATEGORY',
  SET_FIX_TEMPLATE_TYPE: 'fixRequest/SET_FIX_TEMPLATE_TYPE',
  SET_FIX_TITLE: 'fixRequest/SET_FIX_TITLE',
  SET_FIX_DESCRIPTION: 'fixRequest/SET_FIX_DESCRIPTION',
  SET_FIX_SECTION_TITLE: 'fixRequest/SET_FIX_SECTION_TITLE',
  SET_FIX_SECTION_DETAILS: 'fixRequest/SET_FIX_SECTION_DETAILS',
  SET_FIX_ADDRESS: 'fixRequest/SET_FIX_ADDRESS',
  SET_FIX_CITY: 'fixRequest/SET_FIX_CITY',
  SET_FIX_PROVINCE: 'fixRequest/SET_FIX_PROVINCE',
  SET_FIX_POSTAL_CODE: 'fixRequest/SET_FIX_POSTAL_CODE',
  SET_CLIENT_MIN_ESTIMATED_COST: 'fixRequest/SET_CLIENT_MIN_ESTIMATED_COST',
  SET_CLIENT_MAX_ESTIMATED_COST: 'fixRequest/SET_CLIENT_MAX_ESTIMATED_COST',
  SET_FIX_START_DATE: 'fixRequest/SET_FIX_START_DATE',
  SET_FIX_END_DATE: 'fixRequest/SET_FIX_END_DATE',
};

export default FixRequestActionTypesModel;
